---
output:
  html_document:
    theme: readable
    highlight: pygments
    df_print: paged
    keep_md: false
    css: "report.css"
params:
  industry: "Airlines"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(readr)
library(dplyr)
library(ggplot2)
library(stringr)
library(corrplot)
library(extrafont)
library(shiny)
library(reticulate)
library(ggbeeswarm)
library(tidyr)
library(knitr)
library(kableExtra)
library(zoo)

suppressMessages(loadfonts())

path <- str_c("../../data/growth_models/", params$industry, "/")
combined_dat <- read_csv(str_c(path, "combined_data.csv"))
mod_dat <- read_csv(str_c(path, "mod_data.csv"))
rf_metrics <- read_csv(str_c(path, "rf_metrics.csv"))
gb_metrics <- read_csv(str_c(path, "gb_metrics.csv"))
```

<div class="column-center">
```{r}
p(
  str_c(params$industry, " Industry Report"),
  style = "font-family:Times New Roman; color:#0D3B66; font-size:34pt;"
)
p(
  format(Sys.Date(), "%B %Y"),
  style = "font-family:Times New Roman; color:#849698; font-size:24pt;"
)
hr()
br()
p(
  em("Exploratory Data Analysis"),
  style = "font-family:Times New Roman; color:#849698; font-size:20pt;"
)
```

</div>

<div class="column-left-even">

```{r}
p(
  "Distribution of the Response",
  class = "header"
)
```

```{r, fig.height=5, fig.width =12}
mod_dat %>%
  mutate(response = exp(response) - 1.1) %>%
  ggplot() +
  aes(x = response) +
  geom_density(
    color = NA,
    fill = "#0D3B66",
    alpha = 0.8
  ) +
  xlab("Growth (%)") +
  ggtitle("Untransformed") +
  theme_classic() +
  theme(
    text = element_text(family = "Times New Roman"),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 30
    ),
    axis.title.x = element_text(size = 24),
    axis.text.x = element_text(size = 21),
    aspect.ratio = 0.30
  ) +
  coord_cartesian(expand = FALSE, clip = "off")
```


```{r, fig.height=5, fig.width = 12}
mod_dat %>%
  ggplot() +
  aes(x = response) +
  geom_density(
    color = NA,
    fill = "#0D3B66",
    alpha = 0.8
  ) +
  xlab("Log(Growth + 1.1)") +
  ggtitle("Transformed") +
  theme_classic() +
  theme(
    text = element_text(family = "Times New Roman"),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 30
    ),
    axis.text.x = element_text(size = 21),
    axis.title.x = element_text(size = 24),
    aspect.ratio = 0.30
  ) +
  coord_cartesian(expand = FALSE, clip = "off")
```

</div>

<div class="column-right-even">
```{r}
p(
  "Correlation between Covariates and Response",
  class = "header"
)
```

```{r}
corrplot(
  cor(mod_dat),
  method = "shade",
  type = "upper",
  diag = FALSE,
  tl.cex = 1,
  tl.col = "#000000",
  tl.srt = 45,
  cl.pos = "n",
  col = colorRampPalette(colors = c("#EE964B", "#FAF0CA", "#0D3B66"))(200)
)
```
</div>

<div class="column-center">
```{r}
hr()
br()
p(
  em("Model Tuning"),
  style = "font-family:Times New Roman; color:#849698; font-size:20pt;"
)
```

</div>

<div class="column-left-even">

```{r}
p(
  "Random Forest Models",
  class = "header"
)
```

```{r}
rf_metrics %>%
  filter(.metric == "mae") %>%
  ggplot() +
  aes(x = mtry, y = mean, color = as.factor(min_n)) +
  geom_point(size = 2) +
  geom_line(size = 1.5, alpha = 0.8) +
  scale_color_manual(values = c("#EE964B", "#849698", "#A54657", "#0D3B66")) +
  ylab("CV Average") +
  ggtitle("MAE") +
  theme_classic() +
  theme(
    text = element_text(family = "Times New Roman"),
    axis.ticks = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 18
    ),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    legend.position = c(0.75, 0.85),
    legend.background = element_rect(color = "#0D3B66", fill = "#ffffff")
  ) +
  guides(color = guide_legend(nrow = 1, title.position = "top", title.hjust = 0.5)) +
  labs(color = "min_n") +
  coord_cartesian(clip = "off") 
```


```{r}
rf_metrics %>%
  filter(.metric == "rmse") %>%
  ggplot() +
  aes(x = mtry, y = mean, color = as.factor(min_n)) +
  geom_point(size = 2) +
  geom_line(size = 1.5, alpha = 0.8) +
  scale_color_manual(values = c("#EE964B", "#849698", "#A54657", "#0D3B66")) +
  ylab("CV Average") +
  ggtitle("RMSE") +
  theme_classic() +
  theme(
    text = element_text(family = "Times New Roman"),
    axis.ticks = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 18
    ),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 12),
    legend.position = c(0.75, 0.85),
    legend.background = element_rect(color = "#0D3B66", fill = "#ffffff")
  ) +
  guides(color = guide_legend(nrow = 1, title.position = "top", title.hjust = 0.5)) +
  labs(color = "min_n") +
  coord_cartesian(clip = "off") 
```



</div>

<div class="column-right-even">

```{r}
p(
  "Gradient Boosted Models",
  class = "header"
)
```

```{r}
gb_metrics %>%
  filter(.metric == "mae") %>%
  mutate(learn_rate = str_c("learn_rate: ", learn_rate)) %>%
  ggplot() +
  aes(x = mtry, y = mean, color = as.factor(tree_depth)) +
  geom_point(size = 2) +
  geom_line(size = 1.5, alpha = 0.8) +
  facet_wrap(~as.factor(learn_rate), nrow = 1) +
  scale_color_manual(values = c("#EE964B", "#849698", "#A54657", "#0D3B66")) +
  ylab("CV Average") +
  ggtitle("MAE") +
  theme_bw() +
  theme(
    text = element_text(family = "Times New Roman"),
    axis.ticks = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 18
    ),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 12),
    legend.position = c(0.75, 0.85),
    legend.background = element_rect(color = "#0D3B66", fill = "#ffffff")
  ) +
  guides(color = guide_legend(nrow = 1, title.position = "top", title.hjust = 0.5)) +
  labs(color = "tree_depth") +
  coord_cartesian(clip = "off") 
```


```{r}
gb_metrics %>%
  filter(.metric == "rmse") %>%
  mutate(learn_rate = str_c("learn_rate: ", learn_rate)) %>%
  ggplot() +
  aes(x = mtry, y = mean, color = as.factor(tree_depth)) +
  geom_point(size = 2) +
  geom_line(size = 1.5, alpha = 0.8) +
  facet_wrap(~as.factor(learn_rate), nrow = 1) +
  scale_color_manual(values = c("#EE964B", "#849698", "#A54657", "#0D3B66")) +
  ylab("CV Average") +
  ggtitle("RMSE") +
  theme_bw() +
  theme(
    text = element_text(family = "Times New Roman"),
    axis.ticks = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 18
    ),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 12),
    legend.position = c(0.75, 0.85),
    legend.background = element_rect(color = "#0D3B66", fill = "#ffffff")
  ) +
  guides(color = guide_legend(nrow = 1, title.position = "top", title.hjust = 0.5)) +
  labs(color = "tree_depth") +
  coord_cartesian(clip = "off") 
```


</div>




<div class="column-center">
```{r}
hr()
br()
p(
  em("Final Models"),
  style = "font-family:Times New Roman; color:#849698; font-size:20pt;"
)
```

```{r}
p(
  "Random Forest Model",
  class = "header"
)
```

</div>

<div class="column-left-even">


```{r}
best_rf <- rf_metrics %>%
  filter(.metric == "mae") %>%
  arrange(mean) %>%
  slice(1)
best_gb <- gb_metrics %>%
  filter(.metric == "mae") %>%
  arrange(mean) %>%
  slice(1)
mod_dat_py <- mod_dat %>%
  select(-response)
response <- mod_dat$response
```

```{python, results="hide"}
import sklearn.ensemble as sk
import shap
import numpy as np
import pandas as pd

mod_data = r.mod_dat_py
response = r.response
min_samp = np.int(r.best_rf.min_n)
mtry = np.int(r.best_rf.mtry)


rfmod = sk.RandomForestRegressor(n_estimators = 200, criterion = "mae", min_samples_leaf = min_samp, max_features = mtry)

rfmod.fit(X = mod_data, y = response)

preds = rfmod.predict(mod_data)

shap_ex = shap.Explainer(rfmod)
shap_vals = shap_ex(mod_data)
shap_expected = shap_ex.expected_value
```


```{r}
train_preds <- py$preds
train_shap <- py$shap_vals$values %>%
  as_tibble() %>%
  magrittr::set_colnames(colnames(mod_dat %>% select(-response)))
expected_value <- py$shap_expected
```

```{r}
variable_values <- mod_dat %>%
  select(-response) %>%
  mutate(
    across(everything(), .fns = ~((.x - min(.x)) / (max(.x) - min(.x))))
  ) %>%
  pivot_longer(
    names_to = "variable",
    values_to = "var_val",
    cols = colnames(.)
  )

important_vars <- train_shap %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = colnames(.)
  ) %>%
  mutate(value = abs(value)) %>%
  group_by(variable) %>%
  summarize(avg_value = mean(value)) %>%
  ungroup() %>%
  arrange(avg_value) %>%
  pull(variable)

train_shap %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = colnames(.)
  ) %>%
  bind_cols(var_val = variable_values$var_val) %>%
  mutate(variable = factor(variable, levels = important_vars)) %>%
  ggplot() +
  geom_quasirandom(
    aes(y = variable, x = value, color = var_val),
    groupOnX = FALSE,
    size = 2
  ) + 
  theme_classic() +
  xlab("SHAP Value") +
  ylab("Variable") +
  scale_color_gradient2(
    high = "#0D3B66",
    mid = "#FAF0CA",
    low = "#A54657",
    midpoint = 0.5,
    breaks = c(0.1, 0.9),
    labels = c("Low", "High")
  ) +
  ggtitle("SHAP Value Summary") +
  labs(color = "Value of Variable") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = c(0.8, 0.2),
    aspect.ratio = 0.75,
    plot.title = element_text(hjust = 0.5, size = 18),
    legend.background = element_rect(color = "#0D3B66", fill = "#ffffff")
  ) +
  guides(
    color = guide_colorbar(
      label = TRUE,
      title.position = "top",
      title.hjust = 0.5,
      ticks = FALSE,
      direction = "horizontal",
      barwidth = unit(1.5, "in"),
      barheight = unit(0.1, "in")
    )
  )
```

</div>

<div class="column-right-even">

<div style="background:#FAF0CA; border:black solid 3px; margin-left:20px; margin-right:20px;">

```{r}
resid <- train_preds %>%
  as_tibble() %>%
  rename(predict = value) %>%
  bind_cols(actual = mod_dat$response) %>%
  mutate(across(everything(), ~(exp(.x) - 1.1))) %>%
  mutate(differences = actual - predict) %>%
  pull(differences)
p(
  tags$u(tags$b("Model Info and Metrics")),
  style = "font-family:Times New Roman; font-size:14pt"
)
tags$ul(
  tags$li(str_c("min_n: ", best_rf$min_n, ", mtry: ", best_rf$mtry)),
  tags$li(str_c("Mean Absolute Error: ", round(mean(abs(resid)), 4))),
  tags$li(str_c("Root Mean Squared Error: ", round(sqrt(mean(resid^2)), 4))),
  style = "text-align:left;font-family:Times New Roman;margin-left:20px"
)
```
</div>

```{r, fig.width = 10, fig.height = 4}
br()
ggplot() +
  aes(x = resid) +
  geom_density(
    color = NA,
    fill = "#A54657",
    alpha = 0.8
  ) +
  xlab("Residuals") +
  ggtitle("Density of the Residuals") +
  theme_classic() +
  theme(
    aspect.ratio = 0.3,
    text = element_text(family = "Times New Roman"),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 24
    ),
    axis.text.x = element_text(size = 16),
    axis.title.x = element_text(size = 18)
  ) +
  coord_cartesian(clip = "off", expand = FALSE)
```

</div>

<div class="column-center">

```{r, fig.width=10, fig.height=4}
train_shap %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = colnames(.)
  ) %>%
  bind_cols(var_val = variable_values$var_val) %>%
  mutate(variable = factor(variable, levels = important_vars)) %>%
  ggplot() +
  aes(x = var_val, y = value) +
  geom_point(
    color = "#849698",
    alpha = 0.8,
    size = 0.5
  ) +
  facet_wrap(~variable, ncol = 5) +
  theme_bw() +
  xlab("Scaled Variable Value") +
  ylab("SHAP Value") +
  ggtitle("SHAP Values vs. Variable Values") +
  theme(
    text = element_text(family = "Times New Roman"),
    aspect.ratio = 0.75,
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
p(
  "Gradient Boosted Model",
  class = "header"
)
```

```{python, results="hide"}
tree_depth = np.int(r.best_gb.tree_depth)
mtry = np.int(r.best_gb.mtry)
learn_rate = np.float(r.best_gb.learn_rate)


gbmod = sk.GradientBoostingRegressor(learning_rate = learn_rate, max_features = mtry, max_depth = tree_depth)

gbmod.fit(X = mod_data, y = response)

preds_gb = gbmod.predict(mod_data)

shap_ex_gb = shap.Explainer(gbmod)
shap_vals_gb = shap_ex_gb(mod_data)
shap_expected_gb = shap_ex_gb.expected_value
```


```{r}
train_preds_gb <- py$preds_gb
train_shap_gb <- py$shap_vals_gb$values %>%
  as_tibble() %>%
  magrittr::set_colnames(colnames(mod_dat %>% select(-response)))
expected_value_gb <- py$shap_expected_gb
```

</div>

<div class="column-left-even">

```{r}
important_vars <- train_shap_gb %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = colnames(.)
  ) %>%
  mutate(value = abs(value)) %>%
  group_by(variable) %>%
  summarize(avg_value = mean(value)) %>%
  ungroup() %>%
  arrange(avg_value) %>%
  pull(variable)

train_shap_gb %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = colnames(.)
  ) %>%
  bind_cols(var_val = variable_values$var_val) %>%
  mutate(variable = factor(variable, levels = important_vars)) %>%
  ggplot() +
  geom_quasirandom(
    aes(y = variable, x = value, color = var_val),
    groupOnX = FALSE,
    size = 2
  ) + 
  theme_classic() +
  xlab("SHAP Value") +
  ylab("Variable") +
  scale_color_gradient2(
    high = "#0D3B66",
    mid = "#FAF0CA",
    low = "#A54657",
    midpoint = 0.5,
    breaks = c(0.1, 0.9),
    labels = c("Low", "High")
  ) +
  ggtitle("SHAP Value Summary") +
  labs(color = "Value of Variable") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = c(0.8, 0.2),
    aspect.ratio = 0.75,
    plot.title = element_text(hjust = 0.5, size = 18),
    legend.background = element_rect(color = "#0D3B66", fill = "#ffffff")
  ) +
  guides(
    color = guide_colorbar(
      label = TRUE,
      title.position = "top",
      title.hjust = 0.5,
      ticks = FALSE,
      direction = "horizontal",
      barwidth = unit(1.5, "in"),
      barheight = unit(0.1, "in")
    )
  )
```

</div>

<div class="column-right-even">

<div style="background:#FAF0CA; border:black solid 3px; margin-left:20px; margin-right:20px;">

```{r}
resid <- train_preds_gb %>%
  as_tibble() %>%
  rename(predict = value) %>%
  bind_cols(actual = mod_dat$response) %>%
  mutate(across(everything(), ~(exp(.x) - 1.1))) %>%
  mutate(differences = actual - predict) %>%
  pull(differences)
p(
  tags$u(tags$b("Model Info and Metrics")),
  style = "font-family:Times New Roman; font-size:14pt"
)
tags$ul(
  tags$li(str_c("learn_rate: ", best_gb$learn_rate, ", mtry: ", best_gb$mtry, ", tree_depth: ", best_gb$tree_depth)),
  tags$li(str_c("Mean Absolute Error: ", round(mean(abs(resid)), 4))),
  tags$li(str_c("Root Mean Squared Error: ", round(sqrt(mean(resid^2)), 4))),
  style = "text-align:left;font-family:Times New Roman;margin-left:20px"
)
```
</div>

```{r, fig.width = 10, fig.height = 4}
br()
ggplot() +
  aes(x = resid) +
  geom_density(
    color = NA,
    fill = "#A54657",
    alpha = 0.8
  ) +
  xlab("Residuals") +
  ggtitle("Density of the Residuals") +
  theme_classic() +
  theme(
    aspect.ratio = 0.3,
    text = element_text(family = "Times New Roman"),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(
      hjust = 0.5,
      size = 24
    ),
    axis.text.x = element_text(size = 16),
    axis.title.x = element_text(size = 18)
  ) +
  coord_cartesian(clip = "off", expand = FALSE)
```

</div>

<div class="column-center">

```{r, fig.width=10, fig.height=4}
train_shap_gb %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = colnames(.)
  ) %>%
  bind_cols(var_val = variable_values$var_val) %>%
  mutate(variable = factor(variable, levels = important_vars)) %>%
  ggplot() +
  aes(x = var_val, y = value) +
  geom_point(
    color = "#849698",
    alpha = 0.8,
    size = 0.5
  ) +
  facet_wrap(~variable, ncol = 5) +
  theme_bw() +
  xlab("Scaled Variable Value") +
  ylab("SHAP Value") +
  ggtitle("SHAP Values vs. Variable Values") +
  theme(
    text = element_text(family = "Times New Roman"),
    aspect.ratio = 0.75,
    plot.title = element_text(hjust = 0.5)
  )
```

</div>





<div class="column-center">
```{r}
hr()
br()
p(
  em("Future Predictions"),
  style = "font-family:Times New Roman; color:#849698; font-size:20pt;"
)
```

```{r}
most_recent <- combined_dat %>%
  group_by(ticker) %>%
  arrange(quarter) %>%
  mutate(across(everything(), .fns = ~na.locf(.x, na.rm = FALSE))) %>%
  filter(quarter == max(quarter)) %>%
  slice(1) %>%
  ungroup() %>%
  drop_na() %>%
  filter(
    pe_ratio < 5000,
    price_to_book_ratio < 5000,
    price_to_sales_ratio < 5000,
    price_to_fcf_ratio < 5000,
    debt_to_equity_ratio < 5000
  )

newdata <- most_recent %>%
  select(
    colnames(
      mod_dat %>%
        select(-response)
    )
  ) # %>%
  # replace_na(
  #   list(
  #     avg_pct_change = median(mod_dat$avg_pct_change, na.rm = TRUE),
  #     sd_pct_change = median(mod_dat$sd_pct_change, na.rm = TRUE),
  #     avg_vol = median(mod_dat$avg_vol, na.rm = TRUE),
  #     pe_ratio = median(mod_dat$pe_ratio, na.rm = TRUE),
  #     price_to_sales_ratio = median(mod_dat$price_to_sales_ratio, na.rm = TRUE),
  #     price_to_book_ratio = median(mod_dat$price_to_book_ratio, na.rm = TRUE),
  #     price_to_fcf_ratio = median(mod_dat$price_to_fcf_ratio, na.rm = TRUE),
  #     debt_to_equity_ratio = median(mod_dat$debt_to_equity_ratio, na.rm = TRUE),
  #     pays_dividend = 0,
  #     dividend_yield = 0
  #   )
  # )

tickers <- most_recent$ticker
```

```{python}
dat = r.newdata
new_preds_gb = gbmod.predict(dat)
new_preds_rf = rfmod.predict(dat)

new_shap_rf = shap_ex.shap_values(dat)
new_shap_gb = shap_ex_gb.shap_values(dat)
```


</div>

<div class="column-center">

```{r}
tibble(
  ticker = tickers,
  quarter = str_replace(most_recent$quarter, "\\.", " Q"),
  price = str_c("$", round(most_recent$avg_price, 2)),
  pred_rf = py$new_preds_rf,
  pred_gb = str_c(round(py$new_preds_gb * 100, 2), "%")
) %>%
  arrange(desc(pred_rf)) %>%
  mutate(pred_rf = str_c(round(pred_rf * 100, 2), "%")) %>%
  kbl(
    col.names = c(
      "Company",
      "Quarter",
      "Price",
      "RF Prediction",
      "GB Prediction"
    )
  ) %>%
  kable_classic(html_font = "'Times New Roman'") %>%
  column_spec(
    column = 1:5,
    width = "8em"
  )
```


</div>

<div class="column-left-even">

```{r}
top_3 <- tibble(
  ticker = tickers,
  quarter = str_replace(most_recent$quarter, "\\.", " Q"),
  price = str_c("$", round(most_recent$avg_price, 2)),
  pred_rf = py$new_preds_rf,
  pred_gb = py$new_preds_gb
) %>%
  arrange(desc(pred_rf)) %>%
  slice(1:3)
individual_shap <- py$new_shap_rf %>%
  as.data.frame() %>%
  magrittr::set_colnames(colnames(mod_dat %>% select(-response))) %>%
  mutate(ticker = tickers) %>%
  pivot_longer(
    cols = colnames(select(., -ticker)),
    names_to = "covariate",
    values_to = "shap_val"
  ) %>%
  full_join(
    newdata %>%
      mutate(ticker = tickers) %>%
      pivot_longer(
        cols = colnames(select(., -ticker)),
        names_to = "covariate",
        values_to = "var_val"
      ),
    by = c("ticker", "covariate")
  ) %>%
  full_join(
    py$new_shap_gb %>%
      as.data.frame() %>%
      magrittr::set_colnames(colnames(mod_dat %>% select(-response))) %>%
      mutate(ticker = tickers) %>%
      pivot_longer(
        cols = colnames(select(., -ticker)),
        names_to = "covariate",
        values_to = "shap_val_gb"
      ),
    by = c("ticker", "covariate")
  )
```

```{r}
d <- individual_shap %>%
  filter(ticker == top_3$ticker[1]) %>%
  mutate(covariate = forcats::fct_reorder(covariate, shap_val, abs)) %>%
  arrange(desc(covariate)) %>%
  mutate(
    bar_end = cumsum(shap_val) + c(expected_value),
    bar_start = c(expected_value, head(bar_end, -1)),
    is_positive = shap_val > 0
  ) 
d %>%
  ggplot() +
  aes(
    x = covariate, 
    xmin = as.numeric(covariate) - 0.25, 
    xmax = as.numeric(covariate) + 0.25, 
    ymin = bar_end, 
    ymax = bar_start, 
    label = var_val,
    fill = is_positive
  ) + 
  geom_hline(
    aes(yintercept = expected_value),
    color = "#849698",
    size = 1.5
  ) +
  geom_rect(stat = "identity") +
  scale_fill_manual(values = c("#A54657", "#0D3B66")) +
  coord_flip(clip = "off") +
  geom_segment(
    aes(
      y = bar_end,
      yend = bar_end,
      x = as.numeric(covariate) + 0.25,
      xend = as.numeric(covariate) - 1.25
    ),
    color = "#849698",
    lwd = 1
  ) +
  theme_classic() +
  geom_hline(
    aes(yintercept = top_3$pred_rf[1]),
    color = "#EE964B",
    size = 1.5
  ) +
  scale_y_continuous(
    breaks = expected_value,
    labels = str_c("Baseline:\n", round(expected_value * 100, 1), "%"),
    sec.axis = sec_axis(
      ~.,
      breaks = top_3$pred_rf[1],
      labels = str_c("Model Prediction:\n", round(top_3$pred_rf[1] * 100, 1), "%")
    )
  ) +
  scale_x_discrete(
    labels = rev(str_c(d$covariate, "\n", signif(d$var_val, 3)))
  ) +
  ggtitle(top_3$ticker[1], "RF Prediction Explained") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = "none",
    axis.text.y = element_text(
      family = "Times New Roman",
      size = 10
    ),
    axis.text.x = element_text(
      family = "Times New Roman",
      size = 12,
      hjust = 0.5
    ),
    axis.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
###########################
d <- individual_shap %>%
  filter(ticker == top_3$ticker[2]) %>%
  mutate(covariate = forcats::fct_reorder(covariate, shap_val, abs)) %>%
  arrange(desc(covariate)) %>%
  mutate(
    bar_end = cumsum(shap_val) + c(expected_value),
    bar_start = c(expected_value, head(bar_end, -1)),
    is_positive = shap_val > 0
  ) 
d %>%
  ggplot() +
  aes(
    x = covariate, 
    xmin = as.numeric(covariate) - 0.25, 
    xmax = as.numeric(covariate) + 0.25, 
    ymin = bar_end, 
    ymax = bar_start, 
    label = var_val,
    fill = is_positive
  ) + 
  geom_hline(
    aes(yintercept = expected_value),
    color = "#849698",
    size = 1.5
  ) +
  geom_rect(stat = "identity") +
  scale_fill_manual(values = c("#A54657", "#0D3B66")) +
  coord_flip(clip = "off") +
  geom_segment(
    aes(
      y = bar_end,
      yend = bar_end,
      x = as.numeric(covariate) + 0.25,
      xend = as.numeric(covariate) - 1.25
    ),
    color = "#849698",
    lwd = 1
  ) +
  theme_classic() +
  geom_hline(
    aes(yintercept = top_3$pred_rf[2]),
    color = "#EE964B",
    size = 1.5
  ) +
  scale_y_continuous(
    breaks = expected_value,
    labels = str_c("Baseline:\n", round(expected_value * 100, 1), "%"),
    sec.axis = sec_axis(
      ~.,
      breaks = top_3$pred_rf[2],
      labels = str_c("Model Prediction:\n", round(top_3$pred_rf[2] * 100, 1), "%")
    )
  ) +
  scale_x_discrete(
    labels = rev(str_c(d$covariate, "\n", signif(d$var_val, 3)))
  ) +
  ggtitle(top_3$ticker[2], "RF Prediction Explained") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = "none",
    axis.text.y = element_text(
      family = "Times New Roman",
      size = 10
    ),
    axis.text.x = element_text(
      family = "Times New Roman",
      size = 12,
      hjust = 0.5
    ),
    axis.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
#############################
d <- individual_shap %>%
  filter(ticker == top_3$ticker[3]) %>%
  mutate(covariate = forcats::fct_reorder(covariate, shap_val, abs)) %>%
  arrange(desc(covariate)) %>%
  mutate(
    bar_end = cumsum(shap_val) + c(expected_value),
    bar_start = c(expected_value, head(bar_end, -1)),
    is_positive = shap_val > 0
  ) 
d %>%
  ggplot() +
  aes(
    x = covariate, 
    xmin = as.numeric(covariate) - 0.25, 
    xmax = as.numeric(covariate) + 0.25, 
    ymin = bar_end, 
    ymax = bar_start, 
    label = var_val,
    fill = is_positive
  ) + 
  geom_hline(
    aes(yintercept = expected_value),
    color = "#849698",
    size = 1.5
  ) +
  geom_rect(stat = "identity") +
  scale_fill_manual(values = c("#A54657", "#0D3B66")) +
  coord_flip(clip = "off") +
  geom_segment(
    aes(
      y = bar_end,
      yend = bar_end,
      x = as.numeric(covariate) + 0.25,
      xend = as.numeric(covariate) - 1.25
    ),
    color = "#849698",
    lwd = 1
  ) +
  theme_classic() +
  geom_hline(
    aes(yintercept = top_3$pred_rf[3]),
    color = "#EE964B",
    size = 1.5
  ) +
  scale_y_continuous(
    breaks = expected_value,
    labels = str_c("Baseline:\n", round(expected_value * 100, 1), "%"),
    sec.axis = sec_axis(
      ~.,
      breaks = top_3$pred_rf[3],
      labels = str_c("Model Prediction:\n", round(top_3$pred_rf[3] * 100, 1), "%")
    )
  ) +
  scale_x_discrete(
    labels = rev(str_c(d$covariate, "\n", signif(d$var_val, 3)))
  ) +
  ggtitle(top_3$ticker[3], "RF Prediction Explained") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = "none",
    axis.text.y = element_text(
      family = "Times New Roman",
      size = 10
    ),
    axis.text.x = element_text(
      family = "Times New Roman",
      size = 12,
      hjust = 0.5
    ),
    axis.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
```


</div>

<div class="column-right-even">

```{r}
d <- individual_shap %>%
  filter(ticker == top_3$ticker[1]) %>%
  mutate(covariate = forcats::fct_reorder(covariate, shap_val_gb, abs)) %>%
  arrange(desc(covariate)) %>%
  mutate(
    bar_end = cumsum(shap_val_gb) + c(expected_value_gb),
    bar_start = c(expected_value_gb, head(bar_end, -1)),
    is_positive = shap_val_gb > 0
  ) 
d %>%
  ggplot() +
  aes(
    x = covariate, 
    xmin = as.numeric(covariate) - 0.25, 
    xmax = as.numeric(covariate) + 0.25, 
    ymin = bar_end, 
    ymax = bar_start, 
    label = var_val,
    fill = is_positive
  ) + 
  geom_hline(
    aes(yintercept = expected_value_gb),
    color = "#849698",
    size = 1.5
  ) +
  geom_rect(stat = "identity") +
  scale_fill_manual(values = c("#A54657", "#0D3B66")) +
  coord_flip(clip = "off") +
  geom_segment(
    aes(
      y = bar_end,
      yend = bar_end,
      x = as.numeric(covariate) + 0.25,
      xend = as.numeric(covariate) - 1.25
    ),
    color = "#849698",
    lwd = 1
  ) +
  theme_classic() +
  geom_hline(
    aes(yintercept = top_3$pred_gb[1]),
    color = "#EE964B",
    size = 1.5
  ) +
  scale_y_continuous(
    breaks = expected_value_gb,
    labels = str_c("Baseline:\n", round(expected_value_gb * 100, 1), "%"),
    sec.axis = sec_axis(
      ~.,
      breaks = top_3$pred_gb[1],
      labels = str_c("Model Prediction:\n", round(top_3$pred_gb[1] * 100, 1), "%")
    )
  ) +
  scale_x_discrete(
    labels = rev(str_c(d$covariate, "\n", signif(d$var_val, 3)))
  ) +
  ggtitle(top_3$ticker[1], "GB Prediction Explained") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = "none",
    axis.text.y = element_text(
      family = "Times New Roman",
      size = 10
    ),
    axis.text.x = element_text(
      family = "Times New Roman",
      size = 12,
      hjust = 0.5
    ),
    axis.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
###########################
d <- individual_shap %>%
  filter(ticker == top_3$ticker[2]) %>%
  mutate(covariate = forcats::fct_reorder(covariate, shap_val_gb, abs)) %>%
  arrange(desc(covariate)) %>%
  mutate(
    bar_end = cumsum(shap_val_gb) + c(expected_value_gb),
    bar_start = c(expected_value_gb, head(bar_end, -1)),
    is_positive = shap_val_gb > 0
  ) 
d %>%
  ggplot() +
  aes(
    x = covariate, 
    xmin = as.numeric(covariate) - 0.25, 
    xmax = as.numeric(covariate) + 0.25, 
    ymin = bar_end, 
    ymax = bar_start, 
    label = var_val,
    fill = is_positive
  ) + 
  geom_hline(
    aes(yintercept = expected_value_gb),
    color = "#849698",
    size = 1.5
  ) +
  geom_rect(stat = "identity") +
  scale_fill_manual(values = c("#A54657", "#0D3B66")) +
  coord_flip(clip = "off") +
  geom_segment(
    aes(
      y = bar_end,
      yend = bar_end,
      x = as.numeric(covariate) + 0.25,
      xend = as.numeric(covariate) - 1.25
    ),
    color = "#849698",
    lwd = 1
  ) +
  theme_classic() +
  geom_hline(
    aes(yintercept = top_3$pred_gb[2]),
    color = "#EE964B",
    size = 1.5
  ) +
  scale_y_continuous(
    breaks = expected_value_gb,
    labels = str_c("Baseline:\n", round(expected_value_gb * 100, 1), "%"),
    sec.axis = sec_axis(
      ~.,
      breaks = top_3$pred_gb[2],
      labels = str_c("Model Prediction:\n", round(top_3$pred_gb[2] * 100, 1), "%")
    )
  ) +
  scale_x_discrete(
    labels = rev(str_c(d$covariate, "\n", signif(d$var_val, 3)))
  ) +
  ggtitle(top_3$ticker[2], "GB Prediction Explained") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = "none",
    axis.text.y = element_text(
      family = "Times New Roman",
      size = 10
    ),
    axis.text.x = element_text(
      family = "Times New Roman",
      size = 12,
      hjust = 0.5
    ),
    axis.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
#############################
d <- individual_shap %>%
  filter(ticker == top_3$ticker[3]) %>%
  mutate(covariate = forcats::fct_reorder(covariate, shap_val_gb, abs)) %>%
  arrange(desc(covariate)) %>%
  mutate(
    bar_end = cumsum(shap_val_gb) + c(expected_value_gb),
    bar_start = c(expected_value_gb, head(bar_end, -1)),
    is_positive = shap_val_gb > 0
  ) 
d %>%
  ggplot() +
  aes(
    x = covariate, 
    xmin = as.numeric(covariate) - 0.25, 
    xmax = as.numeric(covariate) + 0.25, 
    ymin = bar_end, 
    ymax = bar_start, 
    label = var_val,
    fill = is_positive
  ) + 
  geom_hline(
    aes(yintercept = expected_value_gb),
    color = "#849698",
    size = 1.5
  ) +
  geom_rect(stat = "identity") +
  scale_fill_manual(values = c("#A54657", "#0D3B66")) +
  coord_flip(clip = "off") +
  geom_segment(
    aes(
      y = bar_end,
      yend = bar_end,
      x = as.numeric(covariate) + 0.25,
      xend = as.numeric(covariate) - 1.25
    ),
    color = "#849698",
    lwd = 1
  ) +
  theme_classic() +
  geom_hline(
    aes(yintercept = top_3$pred_gb[3]),
    color = "#EE964B",
    size = 1.5
  ) +
  scale_y_continuous(
    breaks = expected_value_gb,
    labels = str_c("Baseline:\n", round(expected_value_gb * 100, 1), "%"),
    sec.axis = sec_axis(
      ~.,
      breaks = top_3$pred_gb[3],
      labels = str_c("Model Prediction:\n", round(top_3$pred_gb[3] * 100, 1), "%")
    )
  ) +
  scale_x_discrete(
    labels = rev(str_c(d$covariate, "\n", signif(d$var_val, 3)))
  ) +
  ggtitle(top_3$ticker[3], "GB Prediction Explained") +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position = "none",
    axis.text.y = element_text(
      family = "Times New Roman",
      size = 10
    ),
    axis.text.x = element_text(
      family = "Times New Roman",
      size = 12,
      hjust = 0.5
    ),
    axis.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
```


</div>


<div class="column-center">
```{r}
hr()
br()
```

</div>


